version: "3"
volumes:
  nextcloud:
services:
  tor:
    image: tor
    volumes:
       - ./tor:/var/lib/tor/ 
       - ./torrc:/etc/tor/torrc
    restart: always
  nextcloud:
    image: nextcloud
    volumes:
      - nextcloud:/var/www/html
    restart: always

